### ISSUE TITLE
[Suggestion] Blank lines

### ISSUE THREAD

**Issue by bolach** [MaxITService/ChatGPT-Quick-Buttons-for-your-text#1]
This script is fantastic, thank you! I have a feature request: would you consider adding the ability to preserve blank lines (or multiple line breaks) within the text of CUSTOM PROMPTS? Currently, when I try to include blank lines at the end of a prompt within the settings, they are removed from the generated output.

**Comment by MaxITService** [comment]
I Think this is ChatGPT editor itself that removes blank lines from any pasted input. So it will require some editor script suppression probably. This is hypothesis, but I will investigate.

**Comment by MaxITService** [comment]
> This script is fantastic, thank you! I have a feature request: would you consider adding the ability to preserve blank lines (or multiple line breaks) within the text of CUSTOM PROMPTS? Currently, when I try to include blank lines at the end of a prompt within the settings, they are removed from the generated output.

could you please clarify what you mean or record a video with sharex ? Surprisingly I tested my extension - and it preserves new lines in ChatGPT just fine

**Comment by MaxITService** [comment]
If you want ChatGPT to preserve empty lines, ask it to output inside code block. Otherwise more than one line will be cutted. Does that solve your question ?

**Comment by bolach** [comment]
I was trying to recreate this to record, but now it works every time :s 
Anyway, great. I will keep testing and thank you for the reply.

**Comment by MaxITService** [comment]
addressed, investigated, not reproduceable. possibly something on ChatGPT site
